// <auto-generated />
namespace PMS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddedColumnFinancialYearOnModelCashRequisition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedColumnFinancialYearOnModelCashRequisition));
        
        string IMigrationMetadata.Id
        {
            get { return "201309130748582_AddedColumnFinancialYearOnModelCashRequisition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
